### PR TITLE
Add getBlock and chat messages

### PR DESCRIPTION
**Pull request by pbierhoff**
Addition of 2 functionalities: "echo" and "echo <text>" allow for posting of messages on Minecraft screen, while still allowing non-MC messages to be used within Scratch; "getBlock" retrieves block data from Minecraft. Sensor values are called "BlockType" and "BlockDataType" to avoid naming clashes with BlockData and BlockTypeID variables.

### CODE REVIEW

**Comment by pbierhoff** [comment]
I've used these additions in my own customized version of Scratch2MCPI which I use to teach kids programming and thought they were useful. I can also contribute a Minecraft Map generator written in Scratch - it uses getBlock. Let me know if that would be useful.

**Comment by pbierhoff** [comment]
Added one more commit: this fixes issue where Turtle always shows, even if Turtle is not used. Now needs "turtle:activate" to turn on Turtle.

**Comment by champierre** [comment]
@pbierhoff Thank you very much for the PR.

I added getBlock and echo commands, but did not add "turtle:activate" because it changes the default behavior and will confuse the existing users.

I updated the version information:
https://github.com/scratch2mcpi/scratch2mcpi/blob/master/VERSION

**Comment by pbierhoff** [comment]
Thanks for adding 2 of the 3 changes. Regarding "turtle:activate": I have been using Scratch2MCPI for 2 years, and this year you changed all the function names (used to be "getPlayerPosition", now it is "getPos"). So there is definitely a precedent for changes that confuse existing users. I actually had to go into the source to modify all function names back to the 1.0.0 naming because all my existing programs stopped working. I would sincerely ask you to reconsider the stance on "turtle:activate" because all my programs now have a random diamond block in the Minecraft World, which confuses all my existing users. Actually, we could change the code so that it automatically activates the turtle as soon as "turtle:" commands are used the first time. I'll look into this later, if you're okay with that change.

**Comment by champierre** [comment]
@pbierhoff I added many functions this year, but I think I have not changed the existing functions. "getPos" was "getPos" from the very beginning => https://github.com/scratch2mcpi/scratch2mcpi/blob/21eb039dcff34879f6b54e02d59b4f2a1aac9810/scratch2mcpi.py

Regarding activating turtle, I created a new issue, so that we can keep track:
https://github.com/scratch2mcpi/scratch2mcpi/issues/6

Could you post a sample project that shows a random diamond block?

**Pull request merged**
